### ISSUE TITLE
当上传多个文件且都为空文件时会有问题

### ISSUE THREAD

**Issue by CocaColf** [xiaoxiaojx/publish-sftp#1]
【场景】

有如下场景：
有两个文件分别为  `/test/a.txt` 和 `/test/other/b.txt`，两个文件里面无内容

【现象】

实际只有第一个文件上传成功

**Comment by xiaoxiaojx** [comment]
@CocaColf  非常不好意思 刚看到 pr 谢谢修复
有其他问题可以 https://xiaoxiaojx.github.io/resume/ 扫描里面的微信联系
